export const navbarItems = [
  { label: "Dashboard", href: "/dashboard" },
  { label: "Transactions", href: "/transactions" },
  { label: "Manage", href: "/manage" },
];

export const currencies = [
  {
    value: "USD",
    label: "$ - US Dollar",
    locale: "en-US",
  },
  {
    value: "EUR",
    label: "€ - Euro",
    locale: "de-DE",
  },
  {
    value: "GBP",
    label: "£ - British Pound",
    locale: "en-GB",
  },
  {
    value: "JPY",
    label: "¥ - Japanese Yen",
    locale: "ja-JP",
  },
  {
    value: "AUD",
    label: "$ - Australian Dollar",
    locale: "en-AU",
  },
  {
    value: "CAD",
    label: "$ - Canadian Dollar",
    locale: "en-CA",
  },
  {
    value: "CNY",
    label: "¥ - Chinese Yuan",
    locale: "zh-CN",
  },
  {
    value: "INR",
    label: "₹ - Indian Rupee",
    locale: "en-IN",
  },
  {
    value: "RUB",
    label: "₽ - Russian Ruble",
    locale: "ru-RU",
  },
  {
    value: "BRL",
    label: "R$ - Brazilian Real",
    locale: "pt-BR",
  },
];

export const dashboardGreetingWords = [
  "work!",
  "fancy ✽",
  "right",
  "fast",
  "fun",
  "rock",
  "🕶️🕶️🕶️",
];

export const sampleFinancialData = [
  {
    Date: "2024-01-01",
    "Transaction ID": "TXN001",
    Category: "Salary",
    Amount: 5000,
    Type: "Income",
    Description: "Monthly Salary",
    Month: "January",
    Year: 2024,
    Day: "Monday",
    Account: "Checking",
    Status: "Completed",
  },
  {
    Date: "2024-01-02",
    "Transaction ID": "TXN002",
    Category: "Rent",
    Amount: 1200,
    Type: "Outcome",
    Description: "Apartment Rent",
    Month: "January",
    Year: 2024,
    Day: "Tuesday",
    Account: "Checking",
    Status: "Completed",
  },
  {
    Date: "2024-01-03",
    "Transaction ID": "TXN003",
    Category: "Stocks",
    Amount: 1000,
    Type: "Investment",
    Description: "Stock Purchase",
    Month: "January",
    Year: 2024,
    Day: "Wednesday",
    Account: "Brokerage",
    Status: "Completed",
  },
  {
    Date: "2024-01-05",
    "Transaction ID": "TXN004",
    Category: "Freelance",
    Amount: 1500,
    Type: "Income",
    Description: "Freelance Work",
    Month: "January",
    Year: 2024,
    Day: "Friday",
    Account: "Checking",
    Status: "Completed",
  },
  {
    Date: "2024-01-08",
    "Transaction ID": "TXN005",
    Category: "Groceries",
    Amount: 350,
    Type: "Outcome",
    Description: "Weekly Groceries",
    Month: "January",
    Year: 2024,
    Day: "Monday",
    Account: "Credit Card",
    Status: "Completed",
  },
  {
    Date: "2024-01-10",
    "Transaction ID": "TXN006",
    Category: "Crypto",
    Amount: 500,
    Type: "Investment",
    Description: "Bitcoin Purchase",
    Month: "January",
    Year: 2024,
    Day: "Wednesday",
    Account: "Crypto Wallet",
    Status: "Completed",
  },
  {
    Date: "2024-01-15",
    "Transaction ID": "TXN007",
    Category: "Utilities",
    Amount: 200,
    Type: "Outcome",
    Description: "Electricity Bill",
    Month: "January",
    Year: 2024,
    Day: "Monday",
    Account: "Checking",
    Status: "Completed",
  },
  {
    Date: "2024-01-20",
    "Transaction ID": "TXN008",
    Category: "Dividends",
    Amount: 150,
    Type: "Income",
    Description: "Stock Dividends",
    Month: "January",
    Year: 2024,
    Day: "Saturday",
    Account: "Brokerage",
    Status: "Completed",
  },
  {
    Date: "2024-01-25",
    "Transaction ID": "TXN009",
    Category: "Bonds",
    Amount: 800,
    Type: "Investment",
    Description: "Treasury Bonds",
    Month: "January",
    Year: 2024,
    Day: "Thursday",
    Account: "Brokerage",
    Status: "Completed",
  },
  {
    Date: "2024-02-01",
    "Transaction ID": "TXN010",
    Category: "Salary",
    Amount: 5000,
    Type: "Income",
    Description: "Monthly Salary",
    Month: "February",
    Year: 2024,
    Day: "Thursday",
    Account: "Checking",
    Status: "Completed",
  },
  {
    Date: "2024-02-02",
    "Transaction ID": "TXN011",
    Category: "Rent",
    Amount: 1200,
    Type: "Outcome",
    Description: "Apartment Rent",
    Month: "February",
    Year: 2024,
    Day: "Friday",
    Account: "Checking",
    Status: "Completed",
  },
  {
    Date: "2024-02-05",
    "Transaction ID": "TXN012",
    Category: "ETF",
    Amount: 1200,
    Type: "Investment",
    Description: "ETF Investment",
    Month: "February",
    Year: 2024,
    Day: "Monday",
    Account: "Brokerage",
    Status: "Completed",
  },
  {
    Date: "2024-02-10",
    "Transaction ID": "TXN013",
    Category: "Dining",
    Amount: 180,
    Type: "Outcome",
    Description: "Restaurant",
    Month: "February",
    Year: 2024,
    Day: "Saturday",
    Account: "Credit Card",
    Status: "Completed",
  },
  {
    Date: "2024-02-15",
    "Transaction ID": "TXN014",
    Category: "Consulting",
    Amount: 2000,
    Type: "Income",
    Description: "Consulting Fee",
    Month: "February",
    Year: 2024,
    Day: "Thursday",
    Account: "Checking",
    Status: "Completed",
  },
  {
    Date: "2024-02-20",
    "Transaction ID": "TXN015",
    Category: "Real Estate",
    Amount: 1500,
    Type: "Investment",
    Description: "REIT Investment",
    Month: "February",
    Year: 2024,
    Day: "Tuesday",
    Account: "Brokerage",
    Status: "Completed",
  },
  {
    Date: "2024-03-01",
    "Transaction ID": "TXN016",
    Category: "Salary",
    Amount: 5000,
    Type: "Income",
    Description: "Monthly Salary",
    Month: "March",
    Year: 2024,
    Day: "Friday",
    Account: "Checking",
    Status: "Completed",
  },
  {
    Date: "2024-03-02",
    "Transaction ID": "TXN017",
    Category: "Rent",
    Amount: 1200,
    Type: "Outcome",
    Description: "Apartment Rent",
    Month: "March",
    Year: 2024,
    Day: "Saturday",
    Account: "Checking",
    Status: "Completed",
  },
  {
    Date: "2024-03-05",
    "Transaction ID": "TXN018",
    Category: "Stocks",
    Amount: 1000,
    Type: "Investment",
    Description: "Tech Stocks",
    Month: "March",
    Year: 2024,
    Day: "Tuesday",
    Account: "Brokerage",
    Status: "Completed",
  },
  {
    Date: "2024-03-10",
    "Transaction ID": "TXN019",
    Category: "Bonus",
    Amount: 3000,
    Type: "Income",
    Description: "Performance Bonus",
    Month: "March",
    Year: 2024,
    Day: "Sunday",
    Account: "Checking",
    Status: "Completed",
  },
  {
    Date: "2024-03-15",
    "Transaction ID": "TXN020",
    Category: "Travel",
    Amount: 800,
    Type: "Outcome",
    Description: "Vacation",
    Month: "March",
    Year: 2024,
    Day: "Friday",
    Account: "Credit Card",
    Status: "Completed",
  },
];

export const sampleFinancialDataTable = [
  {
    id: "TXN001",
    date: "2024-01-15",
    description: "Monthly Salary",
    category: "Income",
    type: "Income",
    amount: 5000,
    account: "Checking",
    status: "Completed",
    tags: ["Salary", "Recurring"],
  },
  {
    id: "TXN002",
    date: "2024-01-16",
    description: "Apartment Rent",
    category: "Housing",
    type: "Expense",
    amount: -1200,
    account: "Checking",
    status: "Completed",
    tags: ["Rent", "Recurring"],
  },
  {
    id: "TXN003",
    date: "2024-01-17",
    description: "Stock Investment",
    category: "Investments",
    type: "Investment",
    amount: -1000,
    account: "Brokerage",
    status: "Completed",
    tags: ["Stocks", "Long-term"],
  },
  {
    id: "TXN004",
    date: "2024-01-18",
    description: "Freelance Work",
    category: "Income",
    type: "Income",
    amount: 1500,
    account: "Checking",
    status: "Completed",
    tags: ["Freelance", "Side Income"],
  },
  {
    id: "TXN005",
    date: "2024-01-19",
    description: "Groceries",
    category: "Food",
    type: "Expense",
    amount: -350,
    account: "Credit Card",
    status: "Completed",
    tags: ["Essentials"],
  },
  {
    id: "TXN006",
    date: "2024-01-20",
    description: "Cryptocurrency Purchase",
    category: "Investments",
    type: "Investment",
    amount: -500,
    account: "Crypto Wallet",
    status: "Completed",
    tags: ["Crypto", "High Risk"],
  },
  {
    id: "TXN007",
    date: "2024-02-01",
    description: "Monthly Salary",
    category: "Income",
    type: "Income",
    amount: 5000,
    account: "Checking",
    status: "Completed",
    tags: ["Salary", "Recurring"],
  },
  {
    id: "TXN008",
    date: "2024-02-02",
    description: "Apartment Rent",
    category: "Housing",
    type: "Expense",
    amount: -1200,
    account: "Checking",
    status: "Completed",
    tags: ["Rent", "Recurring"],
  },
  {
    id: "TXN009",
    date: "2024-02-03",
    description: "ETF Investment",
    category: "Investments",
    type: "Investment",
    amount: -1200,
    account: "Brokerage",
    status: "Completed",
    tags: ["ETF", "Diversified"],
  },
  {
    id: "TXN010",
    date: "2024-02-10",
    description: "Restaurant Dinner",
    category: "Dining",
    type: "Expense",
    amount: -180,
    account: "Credit Card",
    status: "Completed",
    tags: ["Entertainment"],
  },
  {
    id: "TXN011",
    date: "2024-02-15",
    description: "Consulting Fee",
    category: "Income",
    type: "Income",
    amount: 2000,
    account: "Checking",
    status: "Completed",
    tags: ["Consulting", "Side Income"],
  },
  {
    id: "TXN012",
    date: "2024-02-20",
    description: "REIT Investment",
    category: "Investments",
    type: "Investment",
    amount: -1500,
    account: "Brokerage",
    status: "Completed",
    tags: ["Real Estate", "REIT"],
  },
  {
    id: "TXN013",
    date: "2024-03-01",
    description: "Monthly Salary",
    category: "Income",
    type: "Income",
    amount: 5000,
    account: "Checking",
    status: "Completed",
    tags: ["Salary", "Recurring"],
  },
  {
    id: "TXN014",
    date: "2024-03-02",
    description: "Apartment Rent",
    category: "Housing",
    type: "Expense",
    amount: -1200,
    account: "Checking",
    status: "Completed",
    tags: ["Rent", "Recurring"],
  },
  {
    id: "TXN015",
    date: "2024-03-05",
    description: "Tech Stocks",
    category: "Investments",
    type: "Investment",
    amount: -1000,
    account: "Brokerage",
    status: "Completed",
    tags: ["Stocks", "Tech"],
  },
  {
    id: "TXN016",
    date: "2024-03-10",
    description: "Performance Bonus",
    category: "Income",
    type: "Income",
    amount: 3000,
    account: "Checking",
    status: "Completed",
    tags: ["Bonus", "One-time"],
  },
  {
    id: "TXN017",
    date: "2024-03-15",
    description: "Vacation Trip",
    category: "Travel",
    type: "Expense",
    amount: -800,
    account: "Credit Card",
    status: "Completed",
    tags: ["Travel", "Leisure"],
  },
  {
    id: "TXN018",
    date: "2024-03-20",
    description: "Stock Dividends",
    category: "Income",
    type: "Income",
    amount: 150,
    account: "Brokerage",
    status: "Completed",
    tags: ["Dividends", "Passive Income"],
  },
];
