export const navbarItems = [
  { label: "Dashboard", href: "/dashboard" },
  { label: "Transactions", href: "/transactions" },
  { label: "Manage", href: "/manage" },
];

export const currencies = [
  {
    value: "USD",
    label: "$ - US Dollar",
    locale: "en-US",
  },
  {
    value: "EUR",
    label: "€ - Euro",
    locale: "de-DE",
  },
  {
    value: "GBP",
    label: "£ - British Pound",
    locale: "en-GB",
  },
  {
    value: "JPY",
    label: "¥ - Japanese Yen",
    locale: "ja-JP",
  },
  {
    value: "AUD",
    label: "$ - Australian Dollar",
    locale: "en-AU",
  },
  {
    value: "CAD",
    label: "$ - Canadian Dollar",
    locale: "en-CA",
  },
  {
    value: "CNY",
    label: "¥ - Chinese Yuan",
    locale: "zh-CN",
  },
  {
    value: "INR",
    label: "₹ - Indian Rupee",
    locale: "en-IN",
  },
  {
    value: "RUB",
    label: "₽ - Russian Ruble",
    locale: "ru-RU",
  },
  {
    value: "BRL",
    label: "R$ - Brazilian Real",
    locale: "pt-BR",
  },
];

export const dashboardGreetingWords = [
  "work!",
  "fancy ✽",
  "right",
  "fast",
  "fun",
  "rock",
  "🕶️🕶️🕶️",
];

export const sampleFinancialData = [
  {
    Date: "2024-01-01",
    "Transaction ID": "TXN001",
    Category: "Salary",
    Amount: 5000,
    Type: "Income",
    Description: "Monthly Salary",
    Month: "January",
    Year: 2024,
    Day: "Monday",
    Account: "Checking",
    Status: "Completed",
  },
  {
    Date: "2024-01-02",
    "Transaction ID": "TXN002",
    Category: "Rent",
    Amount: 1200,
    Type: "Outcome",
    Description: "Apartment Rent",
    Month: "January",
    Year: 2024,
    Day: "Tuesday",
    Account: "Checking",
    Status: "Completed",
  },
  {
    Date: "2024-01-03",
    "Transaction ID": "TXN003",
    Category: "Stocks",
    Amount: 1000,
    Type: "Investment",
    Description: "Stock Purchase",
    Month: "January",
    Year: 2024,
    Day: "Wednesday",
    Account: "Brokerage",
    Status: "Completed",
  },
  {
    Date: "2024-01-05",
    "Transaction ID": "TXN004",
    Category: "Freelance",
    Amount: 1500,
    Type: "Income",
    Description: "Freelance Work",
    Month: "January",
    Year: 2024,
    Day: "Friday",
    Account: "Checking",
    Status: "Completed",
  },
  {
    Date: "2024-01-08",
    "Transaction ID": "TXN005",
    Category: "Groceries",
    Amount: 350,
    Type: "Outcome",
    Description: "Weekly Groceries",
    Month: "January",
    Year: 2024,
    Day: "Monday",
    Account: "Credit Card",
    Status: "Completed",
  },
  {
    Date: "2024-01-10",
    "Transaction ID": "TXN006",
    Category: "Crypto",
    Amount: 500,
    Type: "Investment",
    Description: "Bitcoin Purchase",
    Month: "January",
    Year: 2024,
    Day: "Wednesday",
    Account: "Crypto Wallet",
    Status: "Completed",
  },
  {
    Date: "2024-01-15",
    "Transaction ID": "TXN007",
    Category: "Utilities",
    Amount: 200,
    Type: "Outcome",
    Description: "Electricity Bill",
    Month: "January",
    Year: 2024,
    Day: "Monday",
    Account: "Checking",
    Status: "Completed",
  },
  {
    Date: "2024-01-20",
    "Transaction ID": "TXN008",
    Category: "Dividends",
    Amount: 150,
    Type: "Income",
    Description: "Stock Dividends",
    Month: "January",
    Year: 2024,
    Day: "Saturday",
    Account: "Brokerage",
    Status: "Completed",
  },
  {
    Date: "2024-01-25",
    "Transaction ID": "TXN009",
    Category: "Bonds",
    Amount: 800,
    Type: "Investment",
    Description: "Treasury Bonds",
    Month: "January",
    Year: 2024,
    Day: "Thursday",
    Account: "Brokerage",
    Status: "Completed",
  },
  {
    Date: "2024-02-01",
    "Transaction ID": "TXN010",
    Category: "Salary",
    Amount: 5000,
    Type: "Income",
    Description: "Monthly Salary",
    Month: "February",
    Year: 2024,
    Day: "Thursday",
    Account: "Checking",
    Status: "Completed",
  },
  {
    Date: "2024-02-02",
    "Transaction ID": "TXN011",
    Category: "Rent",
    Amount: 1200,
    Type: "Outcome",
    Description: "Apartment Rent",
    Month: "February",
    Year: 2024,
    Day: "Friday",
    Account: "Checking",
    Status: "Completed",
  },
  {
    Date: "2024-02-05",
    "Transaction ID": "TXN012",
    Category: "ETF",
    Amount: 1200,
    Type: "Investment",
    Description: "ETF Investment",
    Month: "February",
    Year: 2024,
    Day: "Monday",
    Account: "Brokerage",
    Status: "Completed",
  },
  {
    Date: "2024-02-10",
    "Transaction ID": "TXN013",
    Category: "Dining",
    Amount: 180,
    Type: "Outcome",
    Description: "Restaurant",
    Month: "February",
    Year: 2024,
    Day: "Saturday",
    Account: "Credit Card",
    Status: "Completed",
  },
  {
    Date: "2024-02-15",
    "Transaction ID": "TXN014",
    Category: "Consulting",
    Amount: 2000,
    Type: "Income",
    Description: "Consulting Fee",
    Month: "February",
    Year: 2024,
    Day: "Thursday",
    Account: "Checking",
    Status: "Completed",
  },
  {
    Date: "2024-02-20",
    "Transaction ID": "TXN015",
    Category: "Real Estate",
    Amount: 1500,
    Type: "Investment",
    Description: "REIT Investment",
    Month: "February",
    Year: 2024,
    Day: "Tuesday",
    Account: "Brokerage",
    Status: "Completed",
  },
  {
    Date: "2024-03-01",
    "Transaction ID": "TXN016",
    Category: "Salary",
    Amount: 5000,
    Type: "Income",
    Description: "Monthly Salary",
    Month: "March",
    Year: 2024,
    Day: "Friday",
    Account: "Checking",
    Status: "Completed",
  },
  {
    Date: "2024-03-02",
    "Transaction ID": "TXN017",
    Category: "Rent",
    Amount: 1200,
    Type: "Outcome",
    Description: "Apartment Rent",
    Month: "March",
    Year: 2024,
    Day: "Saturday",
    Account: "Checking",
    Status: "Completed",
  },
  {
    Date: "2024-03-05",
    "Transaction ID": "TXN018",
    Category: "Stocks",
    Amount: 1000,
    Type: "Investment",
    Description: "Tech Stocks",
    Month: "March",
    Year: 2024,
    Day: "Tuesday",
    Account: "Brokerage",
    Status: "Completed",
  },
  {
    Date: "2024-03-10",
    "Transaction ID": "TXN019",
    Category: "Bonus",
    Amount: 3000,
    Type: "Income",
    Description: "Performance Bonus",
    Month: "March",
    Year: 2024,
    Day: "Sunday",
    Account: "Checking",
    Status: "Completed",
  },
  {
    Date: "2024-03-15",
    "Transaction ID": "TXN020",
    Category: "Travel",
    Amount: 800,
    Type: "Outcome",
    Description: "Vacation",
    Month: "March",
    Year: 2024,
    Day: "Friday",
    Account: "Credit Card",
    Status: "Completed",
  },
];

export const sampleFinancialDataTable = [
  {
    id: "TXN001",
    date: "2024-01-15",
    description: "Monthly Salary",
    category: "Income",
    type: "Income",
    amount: 5000,
    account: "Checking",
    status: "Completed",
    tags: ["Salary", "Recurring"],
  },
  {
    id: "TXN002",
    date: "2024-01-16",
    description: "Apartment Rent",
    category: "Housing",
    type: "Expense",
    amount: -1200,
    account: "Checking",
    status: "Completed",
    tags: ["Rent", "Recurring"],
  },
  {
    id: "TXN003",
    date: "2024-01-17",
    description: "Stock Investment",
    category: "Investments",
    type: "Investment",
    amount: -1000,
    account: "Brokerage",
    status: "Completed",
    tags: ["Stocks", "Long-term"],
  },
  {
    id: "TXN004",
    date: "2024-01-18",
    description: "Freelance Work",
    category: "Income",
    type: "Income",
    amount: 1500,
    account: "Checking",
    status: "Completed",
    tags: ["Freelance", "Side Income"],
  },
  {
    id: "TXN005",
    date: "2024-01-19",
    description: "Groceries",
    category: "Food",
    type: "Expense",
    amount: -350,
    account: "Credit Card",
    status: "Completed",
    tags: ["Essentials"],
  },
  {
    id: "TXN006",
    date: "2024-01-20",
    description: "Cryptocurrency Purchase",
    category: "Investments",
    type: "Investment",
    amount: -500,
    account: "Crypto Wallet",
    status: "Completed",
    tags: ["Crypto", "High Risk"],
  },
  {
    id: "TXN007",
    date: "2024-02-01",
    description: "Monthly Salary",
    category: "Income",
    type: "Income",
    amount: 5000,
    account: "Checking",
    status: "Completed",
    tags: ["Salary", "Recurring"],
  },
  {
    id: "TXN008",
    date: "2024-02-02",
    description: "Apartment Rent",
    category: "Housing",
    type: "Expense",
    amount: -1200,
    account: "Checking",
    status: "Completed",
    tags: ["Rent", "Recurring"],
  },
  {
    id: "TXN009",
    date: "2024-02-03",
    description: "ETF Investment",
    category: "Investments",
    type: "Investment",
    amount: -1200,
    account: "Brokerage",
    status: "Completed",
    tags: ["ETF", "Diversified"],
  },
  {
    id: "TXN010",
    date: "2024-02-10",
    description: "Restaurant Dinner",
    category: "Dining",
    type: "Expense",
    amount: -180,
    account: "Credit Card",
    status: "Completed",
    tags: ["Entertainment"],
  },
  {
    id: "TXN011",
    date: "2024-02-15",
    description: "Consulting Fee",
    category: "Income",
    type: "Income",
    amount: 2000,
    account: "Checking",
    status: "Completed",
    tags: ["Consulting", "Side Income"],
  },
  {
    id: "TXN012",
    date: "2024-02-20",
    description: "REIT Investment",
    category: "Investments",
    type: "Investment",
    amount: -1500,
    account: "Brokerage",
    status: "Completed",
    tags: ["Real Estate", "REIT"],
  },
  {
    id: "TXN013",
    date: "2024-03-01",
    description: "Monthly Salary",
    category: "Income",
    type: "Income",
    amount: 5000,
    account: "Checking",
    status: "Completed",
    tags: ["Salary", "Recurring"],
  },
  {
    id: "TXN014",
    date: "2024-03-02",
    description: "Apartment Rent",
    category: "Housing",
    type: "Expense",
    amount: -1200,
    account: "Checking",
    status: "Completed",
    tags: ["Rent", "Recurring"],
  },
  {
    id: "TXN015",
    date: "2024-03-05",
    description: "Tech Stocks",
    category: "Investments",
    type: "Investment",
    amount: -1000,
    account: "Brokerage",
    status: "Completed",
    tags: ["Stocks", "Tech"],
  },
  {
    id: "TXN016",
    date: "2024-03-10",
    description: "Performance Bonus",
    category: "Income",
    type: "Income",
    amount: 3000,
    account: "Checking",
    status: "Completed",
    tags: ["Bonus", "One-time"],
  },
  {
    id: "TXN017",
    date: "2024-03-15",
    description: "Vacation Trip",
    category: "Travel",
    type: "Expense",
    amount: -800,
    account: "Credit Card",
    status: "Completed",
    tags: ["Travel", "Leisure"],
  },
  {
    id: "TXN018",
    date: "2024-03-20",
    description: "Stock Dividends",
    category: "Income",
    type: "Income",
    amount: 150,
    account: "Brokerage",
    status: "Completed",
    tags: ["Dividends", "Passive Income"],
  },
];

export const features = [
  {
    title: "Real-Time Tracking",
    description:
      "See every dollar move instantly — no surprises, just control. (Or watch your balance tank live, anon.)\n\n" +
      "Track transactions as they happen with zero lag. Whether it's a coffee run or a crypto dip-buy, you'll know the exact impact on your net worth in real time. Perfect for anons who live on the edge and need to see the Ls (or Ws) roll in live.",
    primaryImageSrc: "/images/real-time-tracking-primary.jpg",
    secondaryImageSrc: "/images/real-time-tracking-bg.jpg",
  },
  {
    title: "Income & Expense Dashboard",
    description:
      "Visualize all inflows and outflows in one clear dashboard — know exactly where your money goes. (Tendies in, ramen out — cope in real time.)\n\n" +
      "A full-spectrum view of your financial life: salary deposits, side-hustle gains, subscription leaks, and every Uber Eats regret. Interactive charts break it down by category, merchant, or mood — because sometimes you're just stress-spending on energy drinks at 2 AM.",
    primaryImageSrc: "/images/dashboard-primary.jpg",
    secondaryImageSrc: "/images/dashboard-bg.jpg",
  },
  {
    title: "Smart Budgeting",
    description:
      "Set limits that actually work — with AI tips to stop impulse buys. (NGMI if you ignore them.)\n\n" +
      "Create custom budgets per category (or per coping mechanism). The AI watches your patterns like a hawk and drops truth bombs before you buy that $400 mechanical keyboard 'for productivity.' It even suggests cheaper dopamine hits — like instant ramen instead of DoorDash.",
    primaryImageSrc: "/images/budgeting-primary.jpg",
    secondaryImageSrc: "/images/budgeting-bg.jpg",
  },
  {
    title: "Investment Dashboard",
    description:
      "All your stocks, crypto, and ETFs in one clean view. (One place to watch your bags bleed in sync.)\n\n" +
      "Connect your brokerage, wallet, or exchange — see your entire portfolio in one unified dashboard. Real-time P&L, allocation breakdowns, and a 'Regret Index' that spikes every time you check during a dip. Bonus: dark mode so your red candles don’t blind you at 3 AM.",
    primaryImageSrc: "/images/investment-primary.jpg",
    secondaryImageSrc: "/images/investment-bg.jpg",
  },
  {
    title: "Export to CSV",
    description:
      "Download all your data in CSV format — open in Excel, Google Sheets, or your autism-powered spreadsheet.\n\n" +
      "Full data sovereignty. Export transactions, budgets, investment history, or AI insights with one click. Includes metadata like merchant tags, mood ratings, and 'YOLO score.' Feed it into your custom Notion dashboard, Python script, or 47-tab Google Sheet masterpiece.",
    primaryImageSrc: "/images/export-primary.jpg",
    secondaryImageSrc: "/images/export-bg.jpg",
  },
  {
    title: "Spending Alerts",
    description:
      "Gentle nudges before you overspend. (Or loud pings when you're about to YOLO rent.)\n\n" +
      "Custom alerts via push, email, or carrier pigeon. Set thresholds like 'ping me if I spend >$50 on takeout in 24h' or 'scream if I try to buy another NFT.' Includes pre-spend intervention: 'Are you sure you need this limited-edition cat hoodie?'",
    primaryImageSrc: "/images/alerts-primary.jpg",
    secondaryImageSrc: "/images/alerts-bg.jpg",
  },
  {
    title: "Daily AI Insights",
    description:
      "Fresh money tips every morning — personalized, actionable, no spam. (Your daily cope/hope pill delivered at 8 AM.)\n\n" +
      "Your AI financial therapist sends a daily briefing: 'You spent 23% of income on energy drinks — consider sleep.' Or 'Your crypto is down 12%, but your ramen budget is under by $7 — net cope achieved.' Includes one weird trick to save $3/week (compound interest not included).",
    primaryImageSrc: "/images/ai-insights-primary.jpg",
    secondaryImageSrc: "/images/ai-insights-bg.jpg",
  },
];
